---
# Cannot get this to work for some reason
#AWSTemplateFormatVersion: AWSTemplateFormatVersion: '2010-09-09'

Description: This template places a new ElasticSearch cluster into a region.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

# These show up in the console and are expected to be provided by the operator
Parameters:
    Project:
        Description: 'Project name this cluster is has been created for'
        Type: 'String'
        Default: 'Weapon X'

    Creator:
        Description: 'Tool or person creating this cluster'
        Type: 'String'
        Default: 'CloudFormation'

    Environment:
        Description: 'Context the cluster will be used in.  Common values are production, testing and development.'
        Type: 'String'
        Default: 'development'

    Notes:
        Description: 'Notes to apply, normally edited in the console.'
        Type: 'String'
        Default: 'No notes'

    DomainName:
        Description: 'A name for the Amazon ES domain'
        Type: 'String'

    VolumeSize:
        Description: 'The size of the EBS volume for each data node.'
        Type: 'Number'
        Default: 10

    VolumeType:
        Description: 'The EBS volume type to use with the Amazon ES domain, such as standard, gp2, or io1.'
        Type: 'String'
        Default: 'gp2'

    Iops:
        Description: 'The number of I/O operations per second (IOPS) that the volume supports.'
        Type: 'Number'
        Default: 0

    InstanceCount:
        Description: 'The number of data nodes (instances) to use in the Amazon ES domain.'
        Type: 'Number'
        Default: 2

    InstanceType:
        Description: 'The instance type for your data nodes, such as m3.medium.elasticsearch.'
        Type: 'String'
        Default: 't2.small.elasticsearch'

    ElasticsearchVersion:
        Description: 'The version of Elasticsearch to use, such as 5.1.'
        Type: 'String'
        Default: '5.1'

Resources:
    ElasticsearchDomain:
        Type: AWS::Elasticsearch::Domain
        Properties:
            AccessPolicies:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: 'Allow'
                        Principal:
                            AWS: '*'
                        Action: "es:*"
                        Resource:
                            # 'arn:aws:es:us-east-1:846973539254:domain/test/*'
                            'Fn::Join': [ '/', ['Fn::Join': [ ':', [ 'arn:aws:es', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'domain'] ], !Ref 'DomainName', '*' ] ]
            DomainName:
                Ref: DomainName
            EBSOptions:
                EBSEnabled: true
                Iops:
                    Ref: Iops
                VolumeSize:
                    Ref: VolumeSize
                VolumeType:
                    Ref: VolumeType
            ElasticsearchClusterConfig:
                DedicatedMasterEnabled: 'false'
                InstanceCount:
                    Ref: InstanceCount
                InstanceType:
                    Ref: InstanceType
                ZoneAwarenessEnabled: 'true'
            ElasticsearchVersion:
                Ref: ElasticsearchVersion
            SnapshotOptions:
                AutomatedSnapshotStartHour: 0
            Tags:
                - Key: 'Name'
                  Value:
                      'Fn::Join': [ ':', [ 'Search', !Ref 'AWS::StackName' ] ]
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value: 'Log searching'
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value:
                      Ref: 'Notes'

Outputs:
    Endpoint:
        Description: 'The domain-specific endpoint that is used to submit index, search, and data upload requests to an Amazon ES domain.'
        Value: !GetAtt ElasticsearchDomain.DomainEndpoint
